"""
Django settings for LunaAestetica project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-^e5rle1h(-%nj!#^a_6&3b53jjz6#vq(g!ex-3=ipdn5vn4&k8'

DEBUG = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'login',
    'customers',
    'days_hours',
    'meets',
    'offered_services',
    'payments',
    'settings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware', # Attenzione, il CSRF middleware qui blocca le richieste senza token
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LunaAestetica.urls'
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')
#DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'login.authentication.LunaTokenAuthentication', # La tua classe custom
        #'login.authentication.CustomTokenAuthentication', # La tua nuova classe
        #'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False 

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8080',  # Aurelia (se usa questa porta)
    'http://127.0.0.1:9000',  # Aurelia (porta standard)
    'http://127.0.0.1:9001',  # Aurelia 
    'http://127.0.0.1:5173',  # Vite (se lo usi)
    'http://127.0.0.1:3000',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Disable some security features for development
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
    
if not DEBUG:
    
    CORS_ALLOWED_ORIGINS += [
        'https://luna.innovatiolabs.it',
    ]

ALLOWED_HOSTS = ['*'] #if DEBUG else ['luna.innovatiolabs.it', '127.0.0.1', 'localhost']
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'LunaAestetica.wsgi.application'

DATABASES = {
    'default': {
        'NAME': 'luna',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'USER': 'jester',
        'PASSWORD': 'jester',
        'PORT': 5432,
        'HOST': 'localhost'
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


NOTIFIES_KINDS = (
    ('pre','Nuova prenotazione'),
    ('can','Prenotazione cancellata'),
    ('usr','Nuovo utente registrato'),
)

DAY_CHOICES = [(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')]

STATUS_CHOICES = [('PEND', 'In Arrivo'),('CONF', 'Confermato'),('CANC', 'Cancellato'),]

WALLET_TRANSACTION_TYPES = [('RELOAD', 'Ricarica via Stripe'),('PAYMENT', 'Pagamento Appuntamento'),('REFUND', 'Rimborso (Credito)'),('CASH_OUT', 'Rimborso in Contanti (Manuale)'),('ADJUST', 'Rettifica Gestionale'),]

PAYMENT_STATUS_CHOICES = [('UNPAID', 'Da Pagare'),('PARTIAL', 'Acconto Versato'),('PAID', 'Saldato'),('REFUNDED', 'Rimborsato nel Wallet'),]

PAYMENT_CHOICES = [('NONE', 'Pagamento in sede'),('PARTIAL', 'Acconto percentuale'),('FIXED', 'Acconto fisso'),('FULL', 'Saldo totale anticipato'),]

FRONTEND_URL = 'http://localhost:9001'

AUTH_USER_MODEL = 'login.Users'

CARD_FOR_TEST = "4242424242424242" # 4000056655665556, 5555555555554444, 2223003122003222, 5200828282828210, 5105105105105100
CARD_DATE = "12/34"
CVC = "223"