# Generated by Django 5.2.11 on 2026-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PEND', 'In Arrivo'), ('CONF', 'Confermato'), ('CANC', 'Cancellato')], default='PEND', max_length=4),
        ),
    ]
