# Generated by Django 5.2.11 on 2026-03-01 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Da Pagare'), ('PARTIAL', 'Acconto Versato'), ('PAID', 'Saldato'), ('REFUNDED', 'Rimborsato nel Wallet')], default='UNPAID', max_length=10),
        ),
    ]
