# Generated by Django 5.2.11 on 2026-03-01 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0003_appointment_amount_paid_appointment_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('RELOAD', 'Ricarica via Stripe'), ('PAYMENT', 'Pagamento Appuntamento'), ('REFUND', 'Rimborso (Credito)'), ('CASH_OUT', 'Rimborso in Contanti (Manuale)'), ('ADJUST', 'Rettifica Gestionale')], max_length=10)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('stripe_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('affects_wallet_balance', models.BooleanField(default=True, help_text='If False, transaction is only historicalaof a direct stripe payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='meets.appointment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
