# Generated by Django 5.2.11 on 2026-03-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('minute_increment', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Impostazioni Aziendali',
                'db_table': 'business_settings',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_limit_hours', models.IntegerField(default=0)),
                ('modification_limit_hours', models.IntegerField(default=0)),
                ('show_prices_to_customer', models.BooleanField(default=False)),
                ('payment_policy', models.CharField(choices=[('NONE', 'Pagamento in sede'), ('PARTIAL', 'Acconto percentuale'), ('FIXED', 'Acconto fisso'), ('FULL', 'Saldo totale anticipato')], default='NONE', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentuale (es. 30) o importo fisso (es. 10.00)', max_digits=10)),
                ('wallet_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impostazioni Generali',
                'db_table': 'general_settings',
            },
        ),
    ]
