# Generated by Django 5.2.11 on 2026-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['time'],
            },
        ),
    ]
